### ISSUE TITLE
把笔记链接改成相对路径是不是好点呢, 现在下载到本地的阅读体验不太好

### ISSUE THREAD

**Issue by oszhugc** [heibaiying/BigData-Notes#12]

**Comment by heibaiying** [comment]
感谢建议。已增加离线版本，将导航和图片都换成了本地相对路径，Clone 到本地后即可使用。离线版本的入口页为 : **OFFLINE-README.md**，按住 Ctrl 键并点击目录，即可打开对应文章。@oszhugc

**Comment by oszhugc** [comment]
棒棒哒 👍
