### ISSUE TITLE
Kibana也是数据采集工具吗

### ISSUE THREAD

**Issue by ZaNkss** [heibaiying/BigData-Notes#17]
前置的一个文档中，kibana。请问这个也是数据采集的工具吗？

**Comment by zhongjiajie** [comment]
ES 可视化工具

**Comment by heibaiying** [comment]
@ZaNkss Kibana 不是采集工具。常说的 ELK 分别代表 Elasticsearch、Logstash、Kibana； Kibana 是可视化工具，其中的 Logstash 才是采集工具。
