### ISSUE TITLE
Flink核心概念综述.md 的图有问题

### ISSUE THREAD

**Issue by MINCWANG** [heibaiying/BigData-Notes#23]
四、Flink 集群架构
4.1 核心组件 的任务提交流程图中最右边的应该是TaskManager
如下图
![image](https://user-images.githubusercontent.com/33626973/84032035-49ce5100-a9c9-11ea-83ff-4562d167226d.png)

**Comment by heibaiying** [comment]
感谢指正，已经修改 @MINCWANG
