### ISSUE TITLE
大数据学习路线中的日志收集框架的疑问

### ISSUE THREAD

**Issue by alexzhu0592** [heibaiying/BigData-Notes#25]
kibana不算是日志收集，应该算是可视化平台，日志收集框架可以再加一个filebeat

![bigdata-issue](https://user-images.githubusercontent.com/19310037/89876193-e511bb80-dbf0-11ea-8982-344d2dcbbcfc.png)

**Comment by heibaiying** [comment]
已经做了修改，感谢指正 @alexzhu0592
