### ISSUE TITLE
分布式计算框架--MapReduce 中错误内容

### ISSUE THREAD

**Issue by young1lin** [heibaiying/BigData-Notes#27]
WordCountMapper 继承自 Mappe 类，这是一个泛型类，定义如下

WordCountMapper 继承自` Mapper `类，这是一个泛型类，定义如下

**Comment by heibaiying** [comment]
感谢指正，已经修改 @young1lin

**Comment by young1lin** [comment]
没事，我也得感谢你，这些笔记带我之前稍微入门了 Hadoop
