### ISSUE TITLE
博主整理的很赞

### ISSUE THREAD

**Issue by frank-lam** [heibaiying/BigData-Notes#3]
最近刚慢慢转向大数据运维，感文章整理的很赞

**Comment by heibaiying** [comment]
谢谢 :smile:

**Comment by heibaiying** [comment]
谢谢 :smile: @frank-lam

**Comment by frank-lam** [comment]
@heibaiying 近期在学习大数据，感觉你的大数据部分整理的非常棒。是否可以将你的notes加入我的仓库一起维护呀

frank-lam/fullstack-tutorial: 🚀 fullstack tutorial 2019，后台技术栈/架构师之路/全栈开发社区，春招/秋招/校招/面试
https://github.com/frank-lam/fullstack-tutorial

**Comment by wwxxmm1991** [comment]
都是牛人，赞呀

**Comment by heibaiying** [comment]
@frank-lam 可以，你的这个项目我之前就 star 了，非常棒。很荣幸能加入你的仓库一起维护，只要注明出处就可以了

**Comment by frank-lam** [comment]
@heibaiying 好嘞，非常感谢

**Comment by CrownP** [comment]
博主怎么就不更了呢

**Comment by heibaiying** [comment]
@CrownP 最近工作上比较忙，更新会慢一点
